server:
  port: 8080

spring:
  redis:
    host: 124.223.118.214  # ??
    port: 6379 # ??
    password: 123456 # ??
    database: 0 # ???????0?
    jedis:
      pool:
        max-active: 8  # ??????
        max-idle: 8  # ??????????
        min-idle: 2  # ??????????
        max-wait: 1000  # ??????

